### ISSUE TITLE
doesn't work with new simple_form 2.0

### ISSUE THREAD

**Issue by kzonov** [galetahub/ckeditor#91]
ActionView::Template::Error (undefined method `render' for #Ckeditor::Hooks::SimpleFormBuilder::CkeditorInput:0x0000010267f4a0):
