### ISSUE TITLE
Missing methods on setup after upgrading to 4.4.0

### ISSUE THREAD

**Issue by ncuesta** [galetahub/ckeditor#841]
Hi, I started having an issue with some missing methods right after I upgraded the gem to its `4.4.0` version (in a `Rails 5.2.2.1` don't think that's relevant, though) from `4.2.0`.

I have this initializer:

```ruby
# config/initializers/ckeditor.rb
Ckeditor.setup do |config|
  config.assets_languages = ['es', 'en']
  config.assets_plugins = ['image']
end
```

After upgrading the gem, I started getting this error:

```
[APP_ROOT_PATH]/config/initializers/ckeditor.rb:2:in `block in <main>': undefined method `assets_languages=' for Ckeditor:Module
Did you mean?  asset_path= (NoMethodError)
	from [GEM_ROOT_PATH]/ckeditor-4.4.0/lib/ckeditor.rb:108:in `setup'
	from [APP_ROOT_PATH]/config/initializers/ckeditor.rb:1:in `<main>'
[...lengthy backtrace...]
```

which clearly indicates that there is no such method `asset_languages=` (nor `assets_plugins=`, already checked) in the `Ckkeditor` module.

Digging around, I found that the `mattr_accessor`s that generated these methods have been removed in 36a6fcbd44570da3fa2009a37d86c2233b76dff6, but I can't seem to find any reasons for the removal or how can we should specify those options now.

I apologize in advance if I'm missing something that's already documented somewhere, but I'm not finding any info regarding this API change.

Thanks for your time!
Cheers,
Nahuel.

**Comment by fbukevin** [comment]
Got the same error as well.

**Comment by patricklindsay** [comment]
Use `4.3.0` for now.

`4.4.0` was released which removes Ckeditor assets but this should really have been part of v5.

cc @galetahub

**Comment by galetahub** [comment]
Fixed, the release version 4.4.0 has already renamed to 5.0.0 version. So use 4.3.0 version for now without risk for an update

**Comment by gaetanm** [comment]
Hi,

Same trouble here. I tried an update from `4.3.0` to `5.1.0` and I have exactly the same issue. What should I do?
