### PR TITLE
[Doc] update on extract_content_type/extract_dimensions breaking change

### LINKED ISSUE #906: undefined method extract_dimensions
After upgrading to v5, I am faced with this error message

> NoMethodError - undefined method `extract_dimensions' for #<CkeditorPictureUploader:0x00007fbba201a940>
Did you mean?  extract_size:

It seems we have removed the method in SHA e220fc44b75c1a21dd87c8fa98d639a1a3f4a674

There is no issue nor PR indicating this has been done, and the readme/changelog does not mention about this breaking change.

Could you document about the reason behind this change please? Thanks!

### PR DESCRIPTION
**Pull request by lulalala**
Fix #906

### CODE REVIEW

**Comment by lulalala** [comment]
Hi @galetahub could you take a look please? Thanks!

**Comment by galetahub** [comment]
Thanks!
