### ISSUE TITLE
After add plugins - "Uncaught TypeError: CKEDITOR.tools.getIndex is not a function"

### ISSUE THREAD

**Issue by postbud** [galetahub/ckeditor#588]
1. Download **'image2'** plugins and dependencies
2. Create **'ckeditor/plugins'**, unpack plugins .zip
3. Add to 'config.js':
   **config.plugins = 'dialogui,dialog,lineutils,widget,image2';**

console output:
**Uncaught TypeError: CKEDITOR.tools.getIndex is not a function**
in *\*   var index = CKEDITOR.tools.getIndex( widgetsRepo._.upcasts, function( element ) {**

addUpcast   @   plugin.js?t=F0RD:1952
addWidgetProcessors @   plugin.js?t=F0RD:1947
Repository.add  @   plugin.js?t=F0RD:223
CKEDITOR.plugins.add.init   @   plugin.js?t=F0RD:90
(anonymous function)    @   ckeditor.js?body=1:242
CKEDITOR.scriptLoader.load.m    @   ckeditor.js?body=1:222
CKEDITOR.scriptLoader.load.y    @   ckeditor.js?body=1:222
CKEDITOR.scriptLoader.load.s    @   ckeditor.js?body=1:222
(anonymous function)    @   ckeditor.js?body=1:223

Modified versions of the plugins does not change the situation
Which way to watch?

thanks in advance

**Comment by chrisvel** [comment]
+1 for codesnippet both released versions, same message.

**Comment by gambala** [comment]
Same error, tried addons for both 4.5 and 4.4 version of CKEditor

**Comment by postbud** [comment]
I tried. It does not help

**Comment by Darep** [comment]
image2 plugin is created for CKEditor 4.5.0 which adds the CKEDITOR.tools.getIndex method which the new widget.js needs. So it wouldn't work on CKEditor 4.4.x

Also, Rails is pretty aggressive with caching assets from gems. If you install CKEditor 4.5, try shutting down the Rails server, deleting tmp/cache directory, and starting Rails server. And also clearing the cache in your browser :)

**Comment by postbud** [comment]
***darep*** 
My current gem version CKEditor 4.4.7 (revision 3a35b3d).
Rails is used in production or development mode, the cache is updated , server restar (no difference). Аll dependencies for manual installation are met. They were used version "image2" plugin: 4.5.3, 4.4.8,  4.3.5

**Comment by ktdmedia** [comment]
This is happening with Wordcount and Notification plugin as well.

**Comment by kruzalmighty** [comment]
same issue while integrating emoji plugin.
