### ISSUE TITLE
undefined method extract_dimensions

### ISSUE THREAD

**Issue by lulalala** [galetahub/ckeditor#906]
After upgrading to v5, I am faced with this error message

> NoMethodError - undefined method `extract_dimensions' for #<CkeditorPictureUploader:0x00007fbba201a940>
Did you mean?  extract_size:

It seems we have removed the method in SHA e220fc44b75c1a21dd87c8fa98d639a1a3f4a674

There is no issue nor PR indicating this has been done, and the readme/changelog does not mention about this breaking change.

Could you document about the reason behind this change please? Thanks!
