### ISSUE TITLE
After update Ruby on Rails v8.0.2.1 to 8.0.3 occur error

### ISSUE THREAD

**Issue by Sega100500** [galetahub/ckeditor#949]
I use CKEditor v5.1.3
After update Ruby on Rails v8.0.2.1 to 8.0.3 occur error:
ActionView::Template::Error (undefined method 'add_default_name_and_id' for an instance of ActionView::Helpers::Tags::TextArea)
Caused by: NoMethodError (undefined method 'add_default_name_and_id' for an instance of ActionView::Helpers::Tags::TextArea)

See https://github.com/rails/rails/issues/55737 for full description
